name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Neovim
        uses: rhysd/action-setup-vim@v1
        with:
          neovim: true
          version: stable

      - name: Set up Lua
        uses: leafo/gh-actions-lua@v11
        with:
          luaVersion: "5.1"

      - name: Set up LuaRocks
        uses: leafo/gh-actions-luarocks@v5

      - name: Install test dependencies
        run: luarocks install luacov

      - name: Run tests
        run: bash scripts/test.sh
